#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cloud_vendor
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
